name: 카리나 패치

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 한국 시간 오전 9시

jobs:
  make-file:
    runs-on: ubuntu-latest
    steps:
      - name: 타임존을 한국 시간대로 설정
        run: |
          sudo timedatectl set-timezone Asia/Seoul

      - name: 저장소에 있는 파일 불러오기
        uses: actions/checkout@v4

      - name: Java 17 세팅
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: 컴파일 및 코드 실행
        run: |
          javac App.java
          java App
        env:
          NAVER_KEYWORD: ${{ vars.NAVER_KEYWORD }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: 실행 결과로 나온 파일을 커밋
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "모니터링 파일 저장"
          add: "."

      - name: Push changes to repository
        run: |
          git push origin main