name: 자동 모니터링

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # 매 5분마다 실행 (보장 안됨)

jobs:
  make-file:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소에 있는 파일 불러오기
        uses: actions/checkout@v4

      - name: Java 17 세팅
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: 컴파일 및 코드 실행
        run: |
          javac App.java
          java App
        env:
          NAVER_KEYWORD: ${{ vars.NAVER_KEYWORD }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: 실행 결과로 나온 파일을 커밋
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "모니터링 파일 저장"
          add: "."

      - name: 이전 기사 및 사진 삭제
        run: |
          find ./news-data/ -type f -exec rm -f {} +